### ISSUE TITLE
cmake question

### ISSUE THREAD

**Issue by kingvision** [yulequan/face-alignment-in-3000fps#1]
Hi 
   thank you for your sharing code!
   I got a question : /usr/bin/ld: cannot find -lblas
   can you give me some ideas?
thanks

**Comment by yulequan** [comment]
blas.a  is a  lib which liblinear uses and you must compiler the blas lib according to your platform.
What's more, you can try a absolute path of blas

**Comment by weiyt2014** [comment]
can this code run in windows?

**Comment by yulequan** [comment]
I have add a VS2013 project. you can try it!

**Comment by weiyt2014** [comment]
ok,compile is successful! how to test dataset? run successful can Printhelp(),I want to test datasets,but argc==1,and run printhelp(),and end.so how to test image dataset?

**Comment by yulequan** [comment]
you should modify the paths in the LBF.cpp.

**Comment by weiyt2014** [comment]
Thanks very much! boundingbox_test.txt and keypoints_test.txt need to recreate ? I don't find them!
