### ISSUE TITLE
scaling the bbox

### ISSUE THREAD

**Issue by alfredtofu** [yulequan/face-alignment-in-3000fps#12]
[scale bbox code](https://github.com/yulequan/face-alignment-in-3000fps/blob/master/Facedetect.cpp#L185)

I cannot understand why you do this. If you want to enlarge the bbox, It should be `center_x - width * scale / 2` instead of `x * scale`.

**Comment by yulequan** [comment]
We narrow images when we use opencv face detector. So we should get origin bbx (enlarge opencv return bbx).
Please note the origin of image coordinate does not lie on image center.

**Comment by alfredtofu** [comment]
Yep. You are right since you first [resize the image](https://github.com/yulequan/face-alignment-in-3000fps/blob/master/Facedetect.cpp#L149)
