### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by foresttserof** [yulequan/face-alignment-in-3000fps#16]
你好。我正在学习你的代码，存在一个疑问，就是在Tree的Splitnode()函数中计算candidate_pixel_locations是以candidate_pixel_locations(i,0) = x1 * max_radio_radius_;这种方式进行的，不过后面保存每个节点的feat是feat[0] =candidate_pixel_locations(max_id,0)/max_radio_radius_;
在Tree的训练过程中是使用candidate_pixel_locations来计算坐标，而在其他地方却是使用feat来计算坐标，是不是存在问题呢？

**Comment by yulequan** [comment]
这应该是一个bug.
