### ISSUE TITLE
problem about cmake

### ISSUE THREAD

**Issue by buildtree** [yulequan/face-alignment-in-3000fps#19]
Hello,I'm a rookie,I have a problem about cmake.
When I run 'cmake .'
it presents:
 **CMake Error at CMakeLists.txt:21 (add_executable):
  Cannot find source file:
    ./../liblinear/blas/blas.h
**

The path is correct and the file'blas.h' is exsit

how could i do?

**Comment by yulequan** [comment]
Hi,
You should go to folder build and then run 'cmake'

**Comment by buildtree** [comment]
谢谢您！问题解决了。但是又有新的问题，英语不好就用汉语说啦，见谅...
我用的vs2013+opencv2.4.8，下载了lfpw和helen数据库并生成了Path_Images.txt放到了指定位置，编译成功后，运行调试就闪退，单步执行也没能看出来是怎么回事，用Ctrl+F5显示如下：

```
Loading GlobalParam...
Loading GlobalParam end
Useage:
1. train your own model:    LBF.out  TrainModel
2. test model on dataset:   LBF.out  TestModel
3. test model via a camera: LBF.out  Demo
4. test model on a pic:     LBF.out  Demo xx.jpg
5. test model on pic set:   LBF.out  Demo Img_Path.txt

请按任意键继续. . .
```

在LBF.cpp下我修改的路径是这样的：
```
string modelPath ="D:/Face_alignment_model";                            //新建的文件夹
string dataPath = "D:/Projects_Face_Detection/Datasets/";           //本机上数据库所在路径  
string cascadeName = "haarcascade_frontalface_alt.xml";
```
modelPath是我新建的一个空文件夹Face_alignment_model，里面放有下载的LBF.model和Regressor.model 。这样是否正确？
闪退是哪里的问题呢？希望您有空看到回复，多谢！ @yulequan

**Comment by yulequan** [comment]
你调试的时候应该没有传入命令行参数。
