### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by qiexing** [yulequan/face-alignment-in-3000fps#2]
Hi ,I do the usage step 1-3,then i change the path in LBF.cpp, 
I do both train model and test model all get : Segmentation fault: 11.
I found this problem is related to memory.
My platform is osx10.10.1. 
I need some help!Thanks very much!

**Comment by yulequan** [comment]
My platform is also osx. That's no problem. 
Did you modify the var "modelPath" in LBF.cpp  and make the folder ?

**Comment by qiexing** [comment]
Sorry to disturb you! i did make such a mistake.
Kindly for your reply!

**Comment by eshenxd** [comment]
I need some help，in your code ,you had define a vector<Rect>faces ,but if i want to release it ,some may be wrong .
