### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Anand0793** [yulequan/face-alignment-in-3000fps#20]
Builded the facealignment code in ubuntu 14.04LTS

opencv - 2.4.12

when I run the 
./LBF.out Demo 1.jpg 
Loading GlobalParam...
Loading GlobalParam end
Loading model from LBF.model
End
In image read
detection time = 126.072 ms
Segmentation fault (core dumped)

I need some help!Thanks very much!

**Comment by yulequan** [comment]
Maybe you can modify some hard-code path name in cpp file.
