### ISSUE TITLE
Average testing time for one image

### ISSUE THREAD

**Issue by nishantkapur** [yulequan/face-alignment-in-3000fps#3]
Greetings
can you tell me something about the average testing time for one image through your program.

Thanks

**Comment by yulequan** [comment]
On my Intel i5 macbook , the average testing time is about 16ms.

**Comment by nishantkapur** [comment]
any suggestions on how to compile the code using vs10?

**Comment by yulequan** [comment]
1. configure opencv in your project. 
 2. add blas library to your project . (maybe you should compiler it first)
 3. the linear.cpp linaer.h tron.h tron.cpp  also need to be added to your project, but as source file.

**Comment by nishantkapur** [comment]
Thanks......will configuring boost libraries will be enough?

**Comment by yulequan** [comment]
I haven't used boost before so i cannot provide you some advice.

**Comment by yulequan** [comment]
I don't know....

**Comment by yulequan** [comment]
I have added a VS 2013 project. You can try it.
