### ISSUE TITLE
a problem about blas.a

### ISSUE THREAD

**Issue by weiyt2014** [yulequan/face-alignment-in-3000fps#5]
I just run the code In vs2012. I feel the problem still is blas.a "fatal error LNK1104: 无法打开文件“blas.a”".If I can put  blas.a into the project.The complie is successful,but blas.a is invalid lib. So I want to learn how to complie blas.a in VS in win? Thanks very much.

**Comment by yulequan** [comment]
I have modified my project and it doesn't depend on blas.a now. Please check it.

**Comment by weiyt2014** [comment]
Sorry to interupt you again! I create a project vs 2012.And I add the code in the project. I use opencv 2.4.5.And the complie is failed!.It's still the problem about "fatal error LNK1104: 无法打开文件“blas.a”".      
Is the complie is depending on the vs version and opencv version?

**Comment by yulequan** [comment]
I think you should also add the code of the "liblinear" to your project.
