### ISSUE TITLE
A problem about test time

### ISSUE THREAD

**Issue by weiyt2014** [yulequan/face-alignment-in-3000fps#6]
The code is running successful in win system! Thanks very much!
But I run the code in win ,the test image time 150ms per image. and has a distance to 3000FPS. 
I can see you say test image time 16ms per image. Is it running in win or linux?And if realise the aim in win, it needs what computer  equipment?
Thanks very much!

**Comment by yulequan** [comment]
the alignment time is about 16ms, but the detection time of opencv is about 120ms. so it costs about 150ms per image.

**Comment by weiyt2014** [comment]
Oh,Thanks very much!
The alignment time is about 100ms,but the detection time is about 150ms.So it costs about 250ms per image. I don't know how to result in the difference from yours? Is in win or linux? Is in vs2012 or vs2013? But I feel the problem is not in here!

What's more,the "*.pts“ file in datasets, if the datasets don't have the file,how to test the images? I hope to get some suggestions!

Thanks very much again!

**Comment by yulequan** [comment]
1. Are you under release mode?
2. you can predict it but cannot calculate the error.

**Comment by weiyt2014** [comment]
Thanks very much!The problem is solved!
