### ISSUE TITLE
About the expensive training time

### ISSUE THREAD

**Issue by kaing** [yulequan/face-alignment-in-3000fps#9]
Hello. 

I am using your code to train a new model. But I found the training time is really expensive when I set the number of trees to 300. Do I have to modify the code to parallel computing in order to speed up? I thought since liblinear is called, it should be efficient even without parallel computing...

And also the DeriveBinaryFeat is time consuming too.

Looking forward to your reply. Thank you.

Kai

**Comment by yulequan** [comment]
I have fix the bug and add openMP support, you can download it.
